"""initial_schema_v2

Revision ID: 2acaa8ed4a80
Revises: 6713d96a537a
Create Date: 2025-12-16 13:00:24.448243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2acaa8ed4a80'
down_revision: Union[str, Sequence[str], None] = '6713d96a537a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_column('employees', 'manager_name')
    op.add_column('supervisor_notes', sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('supervisor_notes', 'created_at')
    op.alter_column('work_schedules', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_schedules', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('supervisor_notes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('supervisor_notes', 'create_at')
    op.add_column('employees', sa.Column('manager_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###
