"""setup_venezuela_payroll

Revision ID: 62480ea4b912
Revises: 7acd3a2530db
Create Date: 2025-12-16 22:36:53.037606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62480ea4b912'
down_revision: Union[str, Sequence[str], None] = '7acd3a2530db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_salary', sa.Boolean(), nullable=True),
    sa.Column('calculation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_concepts_id'), 'income_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_income_concepts_tenant_id'), 'income_concepts', ['tenant_id'], unique=False)
    op.create_table('payroll_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('official_minumin_wage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('food_bonus_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ivss_employee_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ivss_employer_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ivss_cap_min_wages', sa.Integer(), nullable=True),
    sa.Column('faov_employee_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('faov_employer_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('calculate_taxes_on_bonuses', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_settings_id'), 'payroll_settings', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_settings_tenant_id'), 'payroll_settings', ['tenant_id'], unique=False)
    op.create_table('employee_recurring_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['income_concepts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_recurring_incomes_id'), 'employee_recurring_incomes', ['id'], unique=False)
    op.add_column('payrolls', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('payrolls', sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('taxable_bonuses', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('non_taxable_bonuses', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payrolls', sa.Column('ivss_base', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('ivss_employee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('faov_employee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('islr_retention', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('ivss_employer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('faov_employer', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payrolls', sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payrolls', sa.Column('details', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'payrolls', 'employees', ['employee_id'], ['id'])
    op.drop_column('payrolls', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payrolls', type_='foreignkey')
    op.drop_column('payrolls', 'details')
    op.drop_column('payrolls', 'net_pay')
    op.drop_column('payrolls', 'faov_employer')
    op.drop_column('payrolls', 'ivss_employer')
    op.drop_column('payrolls', 'total_deductions')
    op.drop_column('payrolls', 'islr_retention')
    op.drop_column('payrolls', 'faov_employee')
    op.drop_column('payrolls', 'ivss_employee')
    op.drop_column('payrolls', 'ivss_base')
    op.drop_column('payrolls', 'total_earnings')
    op.drop_column('payrolls', 'non_taxable_bonuses')
    op.drop_column('payrolls', 'taxable_bonuses')
    op.drop_column('payrolls', 'base_salary')
    op.drop_column('payrolls', 'employee_id')
    op.drop_index(op.f('ix_employee_recurring_incomes_id'), table_name='employee_recurring_incomes')
    op.drop_table('employee_recurring_incomes')
    op.drop_index(op.f('ix_payroll_settings_tenant_id'), table_name='payroll_settings')
    op.drop_index(op.f('ix_payroll_settings_id'), table_name='payroll_settings')
    op.drop_table('payroll_settings')
    op.drop_index(op.f('ix_income_concepts_tenant_id'), table_name='income_concepts')
    op.drop_index(op.f('ix_income_concepts_id'), table_name='income_concepts')
    op.drop_table('income_concepts')
    # ### end Alembic commands ###
