"""add_customer_id_to_quotes

Revision ID: 60f792712e41
Revises: 8fbcc73d6033
Create Date: 2025-12-23 21:00:15.164164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f792712e41'
down_revision: Union[str, Sequence[str], None] = '8fbcc73d6033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('customer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'customer_id')
    # ### end Alembic commands ###
