"""add_salesperson_logic

Revision ID: cbdc2c4d067d
Revises: add_quotes_table
Create Date: 2025-12-16 22:39:48.961816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdc2c4d067d'
down_revision: Union[str, Sequence[str], None] = 'add_quotes_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('salesperson_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('created_by_user_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('issue_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_invoices_salesperson_id'), 'invoices', ['salesperson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_salesperson_id'), table_name='invoices')
    op.drop_column('invoices', 'issue_date')
    op.drop_column('invoices', 'created_by_user_id')
    op.drop_column('invoices', 'salesperson_id')
    # ### end Alembic commands ###
