"""Add level and total_amount columns

Revision ID: 8b652bada164
Revises: 27ec6fb38fea
Create Date: 2025-12-09 15:04:32.209167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b652bada164'
down_revision: Union[str, Sequence[str], None] = '27ec6fb38fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('is_transactional', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'accounts', ['parent_id'], ['id'])
    op.drop_column('accounts', 'description')
    op.add_column('ledger_entries', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ledger_entries_credit_account_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('ledger_entries_debit_account_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'amount')
    op.drop_column('ledger_entries', 'debit_account_id')
    op.drop_column('ledger_entries', 'credit_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('credit_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ledger_entries', sa.Column('debit_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ledger_entries', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ledger_entries_debit_account_id_fkey'), 'ledger_entries', 'accounts', ['debit_account_id'], ['id'])
    op.create_foreign_key(op.f('ledger_entries_credit_account_id_fkey'), 'ledger_entries', 'accounts', ['credit_account_id'], ['id'])
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ledger_entries', 'total_amount')
    op.add_column('accounts', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'parent_id')
    op.drop_column('accounts', 'is_transactional')
    op.drop_column('accounts', 'level')
    # ### end Alembic commands ###
